import "./style/globals.css";

import { Navigation } from "@/components/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body>
        <div className="mx-auto flex max-w-2xl">
          <Navigation />
          <main className="max-w-xl flex-1 border-x border-lightGray">{children}</main>
        </div>
      </body>
    </html>
  );
};
export default RootLayout;
