import "./style/globals.css";

import { Navigation } from "@/components/Navigation";

export const metadata = {
  title: "一流レシピ",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <head>
        <link rel="icon" href="/images/logo/favicon/16×16px/IchiryuRecipe_Favicon_16×16px.png" type="image/png" />
      </head>
      <body className="mx-auto flex max-w-2xl flex-col-reverse items-start font-serif sm:flex-row">
        <Navigation />
        <div className="flex flex-col">
          <main className="w-screen border-x border-lightGray sm:max-w-md">{children}</main>
        </div>
      </body>
    </html>
  );
};
export default RootLayout;
